deterministic_size: 64
category_size: 4
class_size: 4
stochastic_size: ${mul:${class_size},${class_size}}
obs_embed_size: 32
activation_name: ELU
action_size: 1

model:
  _target_: rssm.v2.module.RSSMV2
  representation_config:
    _target_: rssm.base.module.RepresentationConfig
    obs_embed_size: 4096
    hidden_size: ${deterministic_size}
    deterministic_size: ${deterministic_size}
    stochastic_size: ${stochastic_size}
    category_size: ${category_size}
    class_size: ${class_size}
    activation_name: ${activation_name}
  transition_config:
    _target_: rssm.base.module.TransitionConfig
    hidden_size: ${deterministic_size}
    activation_name: ${activation_name}
    deterministic_size: ${deterministic_size}
    stochastic_size: ${stochastic_size}
    action_size: ${action_size}
    category_size: ${category_size}
    class_size: ${class_size}
  encoder_config:
    _target_: cnn.network.EncoderConfig
    linear_sizes:
      _target_: builtins.tuple
      _args_:
        - [0,]
    activation_name: ${activation_name}
    out_activation_name: Identity
    channels:
      _target_: builtins.tuple
      _args_:
        - [16, 32, 64]
    kernel_sizes:
      _target_: builtins.tuple
      _args_:
        - [3, 3, 3]
    strides:
      _target_: builtins.tuple
      _args_:
        - [2, 2, 2]
    paddings:
      _target_: builtins.tuple
      _args_:
        - [1, 1, 1]
    observation_shape:
      _target_: builtins.tuple
      _args_:
        - [3, 64, 64]
  decoder_config:
    _target_: cnn.DecoderConfig
    linear_sizes:
      _target_: builtins.tuple
      _args_:
        - [80, 256]
    activation_name: ${activation_name}
    out_activation_name: Sigmoid
    channels:
      _target_: builtins.tuple
      _args_:
        - [64, 32, 16]
    kernel_sizes:
      _target_: builtins.tuple
      _args_:
        - [4, 4, 4]
    strides:
      _target_: builtins.tuple
      _args_:
        - [2, 2, 2]
    paddings:
      _target_: builtins.tuple
      _args_:
        - [1, 1, 1]
    output_paddings:
      _target_: builtins.tuple
      _args_:
        - [0, 0, 0]
    observation_shape:
      _target_: builtins.tuple
      _args_:
        - [3, 64, 64]
  

datamodule:
  _target_: rssm.dataset.datamodule.ActionObservationDataModule
  data_name: pinpad
  batch_size: 32
  seq_per_batch: 1
  num_workers: 4
  train_transforms:
    _target_: rssm.dataset.augmentation.Transforms
    action_input:
      _target_: torchvision.transforms.Compose
      transforms:
        -
          _target_: rssm.dataset.augmentation.AdditiveNoise
          std: 0.2
    observation_input:
      _target_: torchvision.transforms.Compose
      transforms:
        -
          _target_: rssm.dataset.augmentation.AdditiveNoise
          std: 0.2
  val_transforms:
    _target_: rssm.dataset.augmentation.Transforms

trainer:
  _target_: lightning.Trainer
  accelerator: gpu
  devices:
    - 2
  max_epochs: -1
  gradient_clip_val: 10
  deterministic: true
  precision: 16-mixed
  log_every_n_steps: 1

callbacks:
  -
    _target_: rssm.utils.callback.RichProgressBar
  -
    _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: val_loss
    patience: 200
    verbose: true
  -
    _target_: rssm.v2.callback.LogRSSMV2Output
    every_n_epochs: 100
    indices:
      - 0
      - 1
      - 2
      - 3
      - 20
      - 21
      - 22
      - 23
