name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Install dependencies
        run: |
          uv sync --all-extras
      - name: Run lint
        run: |
          uv run ruff check .
          uv run mypy --strict .
          # uv run pydoclint .
      - name: Run tests
        run: |
          uv run pytest -ra --cov=src --cov-report=term --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
